global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: '192.168.122.40_node-exporter'
    static_configs:
    - targets: ['192.168.122.40:9100']
